import type { Metadata } from "next";

import { getCurrentUser } from "@/api/user/get-current";
import { NavigationMenu } from "@components/NavigationMenu/NavigationMenu";
import { geistMono, geistSans } from "@styles/fonts";
import "@styles/globals.css";

export const metadata: Metadata = {
  title: "Library App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavigationMenu currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
