import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { getCurrentUser } from "@/api/user/get-current";
import { NavigationMenu } from "@components/NavigationMenu/NavigationMenu";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Library App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavigationMenu currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
